### PR TITLE
Rename Library project

### PR DESCRIPTION
**Pull request by mchrupczalski**
optional - change done to initiate PR (Pull Request)

### CODE REVIEW

**Comment by mchrupczalski** [comment]
Hi mate,

I am answering your question on https://forums.iamtimcorey.com/t/attempt-at-dip-code-review/4070
Please wait...

**Comment by Virslandir** [comment]
@mchrupczalski hi, I want to keep your refactored code in the repo, and I also want to keep my original code for reference, and also for other people from the Forum to be able to see and review. 

Could I, say, incorporate your "refactor" branch not in my master, but in my separate branch? Maybe just "glue" your branch to my existing branches?

A vague idea of how I could do this, is: I have "FETCHed" your PR to my local machine. Now I guess that I could just push it to the remote, and that would be it. But what would than happen with the formal PR? Is there a way to do this right out of the PR?

Thanks.

**Comment by mchrupczalski** [comment]
Hi @Virslandir,

I am only using `GitHub` for my personal projects, where I have not had any PRs, so I am not sure if the below will work.
In my daily work, we use `Azure Repos`, where you can change the target branch for the PR.
According to this blog post: [Change Branch](https://github.blog/2016-08-15-change-the-base-branch-of-a-pull-request), you should be able to change it in GitHub as well.
So, create a new branch, name it `refactor_mc` or anything that makes sense to you, and then you should be able to update the PR to pull to the new branch instead of `master`.
Let me know if this cannot be done in GitHub. We can then close this PR, and once you create a new branch, I can create a new PR there.

**Comment by Virslandir** [comment]
@mchrupczalski the blog post gives seemingly clear instructions. I will try it this evening. Thanks!

**Comment by mchrupczalski** [comment]
One more thing I was thinking about is your learning path.
The Console projects are good for learning language but are not so good for learning design principles. That is because the console projects are quite flexible and do not force you to apply any architectural patterns. You may find it easier to grasp some of those concepts if you move to GUI projects. I would recommend WPF as it implies the use of MVVM architectural patterns. WinForms are not good for that, as they do not imply any patterns by default.
So, once you move to WPF, it will make more sense how to make classes UI agnostic and why you want to separate something out. Then you can move back to console projects with the new knowledge, and it will be easier to apply it.

feel free to ping me on Discord if you have any Qs.
I am not sure how to share my discord account link, but here is my username: RohnJambo#2364

**Comment by Virslandir** [comment]
The web projects are the most interesting to me. I have followed Tim in some small projects, such as the [Hotel Management app](https://github.com/Virslandir/HotelApp) which uses RazorPages in .NET 5 (I think it was 5) and also SQL Server and Dapper. I have returned a bit to the first principles, to be able to understand better the structure and dependency flow in the GUI web apps. The razor pages template is full of things that I don't know or understand, but when I revisit the Hotel App now, or start new asp web apps, I expect to have better understanding of the surrounding.

The desktop UI project types do not interest me much, honestly. The web is so interesting to me. I spent a nice amount of time learning about networking, protocols. OSI model, client/server, etc...I find myself drawn to exploring more about the web, while desktop has not had this effect on me.

Thanks for the Discord handle, although I struggle with this platform. I have tried using it multiple times, and each and every time I simply get lost in the servers with hundreds of users, and the conversation is difficult to track...I delete the app every time after a while :))

edit: I have sent you a friend request on Discord.  I am SpiricS#1739.

**Pull request merged**
